### ISSUE TITLE
例假日違法的加班薪資有誤

### ISSUE THREAD

**Issue by yurenju** [g0v/workweek#14]
依照下圖例假日違法加班的薪水有誤，以平均時薪 150 元計算，例假日違法加班第九個小時薪水應為 200 元。

![image](https://cloud.githubusercontent.com/assets/22155/16836698/62c9cb4e-49f1-11e6-89cc-7b33869fcdc1.png)
## 原因

以平均時薪 150 元計算。
- 合法加班八小時以內的狀況下適用[勞基法 24-3 條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=24)，所以薪水為兩倍，但例假日已經給薪，所以額外工資為 1200。
- 違法加班（例如沒有天災）的狀況下適用[勞基法 24-1 與 24-2](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=24)
- 為什麼違法加班的前八個小時給薪是 150 \* 8 原因在[（76）台勞動 字第 1742 號 函](http://laws.mol.gov.tw/Chi/FINT/FINTQRY04.asp?sel_word=%B1%60%A5%CE%A6r%A7O&N1=%B3%D2%B0%CA&N2=1742&Y1=&M1=&D1=&Y2=&M2=&D2=&kw=&sdate=&edate=&keyword=&ktitle=&etype=*&hidHnFtmb=927890366&chkNow=1&EXEC2=%ACd++%B8%DF&datatype=etype&typeid=*&recordNo=1)：事業單位違反上開法令規定，除應依法處理並督責改進外，如勞工已有於例假日出勤之事實，其當日出勤之工資，仍應加倍發給。

**Comment by annua0204** [comment]
你好..不好意思想請問一下..
關於『符合 40 條天災事變突發事件』的『第九個小時後之後』的『加發 2 倍時薪』，關於這個 2 倍的資訊是從何而來的呢？

**Comment by yurenju** [comment]
@annua0204 你好，

就我的理解出自於勞基法 24-3 與 32-3
- [24-3](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=24): 依第三十二條第三項規定，延長工作時間者，按平日每小時工資額加倍發給之。 
- [32-3](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=32): 因天災、事變或突發事件，雇主有使勞工在正常工作時間以外工作之必要者，得將工作時間延長之。但應於延長開始後二十四小時內通知工會；無工會組織者，應報當地主管機關備查。延長之工作時間，雇主應於事後補
  給勞工以適當之休息。

由於勞基法規定假日也有給薪，所以八個小時以下的薪水是一倍。但是超過八個小時後就不在假日給薪範圍，所以變成要乘以 2。

以平均時薪 150 元計算，前八個小時額外工資為 150 \* 8 = 1200，第九個小時薪水為 150 \* 2 = 300

**Comment by annua0204** [comment]
@yurenju 
謝謝您的回覆..因為我剛好有例假日加班的問題，當日剛好加班了 10 個小時，故對於超過 10 小時有所疑問（因為算是公司突發事件，所以應該也包含在 32-2 之中）。
前八個小時沒有問題，有疑問的是超過八個小時的部分。

關於勞基法 
[(87)台勞動二字第039675號](http://www.elite168.com.tw/search_detail_141.htm) : 
勞動基準法第三十九條規定勞工於休假日工作，工資應加倍發給。
勞工假日出勤工作於八小時內，應依前開規定辦理；超過八小時部分，應依同法第二十四條規定辦理。

[第 39 條:](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=39)：
[第三十六條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=36)所定之例假、[第三十七條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=37)所定之休假及[第三十八條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=38)所定之特別休假，工資應由雇主照給。雇主經徵得勞工同意於**休假日工作**者，工資應加倍發給。因季節性關係有趕工必要，經勞工或工會同意照常工作者，亦同。

因為第 39 條並未清楚說明『休假日工作』 是否包含第 36 條的例假。
但因為並在同一條內說明...且我查不到有特別為例假日產生的加班費另做說明。
也查不到例假日產生的加班費，的『加倍』是加幾倍的資訊。
所以我的解讀認為第 39 條就包含了所有的 例假、休假、特別休假，也就是包含 週六休息日 以及 周日例假日。

由於因為週六就算是加班超過了 8 小時，超過的時數也不包含假日給薪範圍，但可以拿到的只有 1又1/3 或是 1又3/2。
所以週日就算是超過了 8 小時，應該也是同週六的算法。

以上為個人淺見，若有誤也請多包涵，謝謝 :)

**Comment by djpcsixth** [comment]
@annua0204 39條條文內的休假日是指**第三十七條所定之休假**，這邊指得是國定假日，不包含第三十六條所定之例假及第三十八條所定之特別休假。您可以再仔細看一次39條條文的第一段。
