### ISSUE TITLE
例假日工作條件應該是"例假日發生了天災、事變或突發事件"或"勞工同意例假日加班"

### ISSUE THREAD

**Issue by chuck-lee** [g0v/workweek#15]
目前UI設計，勾選"例假日發生了天災、事變或突發事件"後還需勾選"勞工同意例假日加班"，才會視為上班。

但依勞基法第40條規定：
`因天災、事變或突發事件，雇主認有繼續工作之必要時，得停止第三十六條至第三十八條所定勞工之假期。`
因此發生天災、事變或突發事件需要上班時，是由雇主直接停止休假，不需經勞工同意。

與此相對，"勞工同意例假日加班"因為不符例假日上班的要件，是違法上班。

所以這兩個條件應該改用radio button而不是checkbox，並修改相關的判定規則。

**Comment by chuck-lee** [comment]
我會處理這個bug

**Comment by chuck-lee** [comment]
我會處理這個bug

**Comment by djpcsixth** [comment]
@chuck-lee  關於例假日加班條件的相關討論，可以參考Close部分的#7 issue。希望更改UI能滿足描述以下三種情境：

第一種，非40條法定原因及程序要件完備，雇主要求勞工例假日加班，勞工拒絕：
**例假日加班除40條法定原因外，加班屬違法，勞工得拒絕之。**

第二種，非40條法定原因及程序要件完備，雇主要求勞工例假日加班，勞工同意並出勤：
例假日加班除40條法定原因外，**雖勞工同意加班仍屬違法**，雇主得處79條罰則，勞工如有出勤之事實，薪資仍應加倍發給，行政函釋裡面沒有提到是否比照40條內容給予補休，應為沒有補休。

第三種，符合40條法定原因及程序要件完備，勞工於例假日加班：
**應給予勞工40條規定之加倍工資及補休。**

這三種情境是互斥的，不會同時發生，每種情境的補償內容也不同，提供給@chuck-lee 大大參考。

**Comment by djpcsixth** [comment]
@chuck-lee 或許可以設計成三個按鈕，供您參考：
1. 例假日發生了天災、事變或突發事件，雇主要求出勤。
2. 非天災、事變或突發事件，勞工同意加班並出勤
3. 非天災、事變或突發事件，勞工拒絕出勤。

**Comment by chuck-lee** [comment]
第三個按鈕有點怪，如果拒絕出勤，照理說計算機的那一天就不會有工時。
如果勞工拒絕然後被強迫出勤．那就會形成和按鈕2一樣的結果。

我想先釐清一下三個按鈕會引發的行為：
1. 例假日發生了天災、事變或突發事件，雇主要求出勤：使用例假日填寫的工時，依合法出勤計算加班費及補休。
2. 非天災、事變或突發事件，勞工同意加班並出勤：使用例假日填寫的工時，依非法出勤計算加班費。
3. 非天災、事變或突發事件，勞工拒絕出勤：例假日填寫的工時不列入計算。
@djpcsixth  是這樣的感覺嗎？

**Comment by chuck-lee** [comment]
是不是在選2的時候直接顯示＂違法加班，勞工可以拒絕出勤＂就好了？
不過這又扯到另一件事情就是，即使加班合法，勞工還是有權拒絕加班啊 XD

**Comment by djpcsixth** [comment]
@chuck-lee 是的，那三種情境如您前篇回應所描述。如您理解的，可以在第三種情境增加補充說明：**例假日填寫的工時不列入計算。**幫助其他使用者理解。

勞基法32條保障勞工加班都應該是在勞資合意的前提下進行。如果雇主有強迫勞工進行加班的行為皆屬違法，可向當地主管機關進行檢舉。第三種情境其實就是描述**雇主要求加班違法，勞工可以拒絕出勤**這項事實，我想如果使用者在填寫完當週工時後，可以直接透過選取按鈕來切換三種不同的情境，展現出對應的工時及工資，應該可以更很有效地幫助使用者區別**例假日加班**可能遇到的三種情境。

補充說明，加班其實應該要檢視以下兩點，但在台灣勞動環境通常直接無視第二點：
1. 雇主要求加班是否合乎勞基法？
2. 是否勞資合意？

**Comment by yurenju** [comment]
推了，謝謝 @djpcsixth 與 @chuck-lee!!
