### ISSUE TITLE
每天工時上限不能超過 24 小時

### ISSUE THREAD

**Issue by yurenju** [g0v/workweek#18]
![screen shot 2016-07-20 at 11 11 05 pm](https://cloud.githubusercontent.com/assets/69736/16991765/4dfae774-4ecf-11e6-80c2-529bccadc00b.png)

**Comment by Rplus** [comment]
這是直接調整網址參數的結果嗎？

**Comment by yurenju** [comment]
@Rplus 單純我自己沒檢查～
