### ISSUE TITLE
兩例中，星期六日是完全禁止加班，故不應有加班費

### ISSUE THREAD

**Issue by git4tw99** [g0v/workweek#7]
兩例中只有在週一到週五加長工時時可能增加加班費；
第六天增加工作時數時要顯示：「除非天災，不然不能加班」，直接維持沒有增加工時的40小時。
例如：填表試算時，我填星期六4小時，二例那欄就會算給我們看加班費，這是不對的；應該在計算機的呈現上就是禁止六日加班，理論上那是不存在的加班費。
所以目前的爭議就是真正真正的弱勢，他真的想要在星期六加班賺點便當費給孩子的話，是被禁止的，兩例制是強迫我休假。就算你是真的缺錢想要上班，但是，你自發性上班僱主也違法…
是故，在缺乏彈性的情況下，可能會導致逆選擇。
當然，如果你有足夠的月薪的情況下，我也是會選週休二日，我從工作以來都是週休二日，此制對我沒有影響，但對於底層的勞工影響非常的大。想賺錢，也沒得賺哦… 法令直接卡死

**Comment by yurenju** [comment]
如同之前在 [Facebook 的討論](https://www.facebook.com/shaohui.chen/posts/10154345216029784?comment_id=10154345244964784&comment_tracking=%7B%22tn%22%3A%22R3%22%7D)

目前網站上的說明已經包含了「除非天災，不然不能加班」：

> 只有在天災、事變或突發事件才可在例假日（如週六、週日）工作。

依照 [勞基法 40 條](http://law.moj.gov.tw/LawClass/LawSingle.aspx?Pcode=N0030001&FLNO=40)

> 因天災、事變或突發事件，雇主認有繼續工作之必要時，得停止第三十六 條至第三十八條所定勞工之假期。但停止假期之工資，應加倍發給，並應於事後補假休息。前項停止勞工假期，應於事後二十四小時內，詳述理由，報請當地主管機關核備。

該加倍工資如果不能稱作「加班費」，實際作法可以為把「加班費」改成「額外工資」，並且於說明加註：

> 下面的「額外工資」欄位包含加班費與例假日上班的工資加倍發給

修改方式我先放在 commit https://github.com/yurenju/workweek/commit/fa3f854b2bc8b23b5c4a1f40949cb1d6efd5e5c5, 這個修改還沒上放去，只是先放在我自己的 repository 裡面預覽。

**Comment by yurenju** [comment]
現在改成這樣， @git4tw99 覺得如何？

![image](https://cloud.githubusercontent.com/assets/22155/16751466/5d78737a-480c-11e6-8e4d-0a0cc0e1d6c5.png)

**Comment by djpcsixth** [comment]
很棒的計算機，關於例假加班問題應該分三種情境處理。很遺憾的是例假日加班相關說明並沒有清楚的表達三種情境的差異，說明欄將工資與違法敘述擺在一起，有點像是將三種情境的內容混在一起談，但明眼人知道這三種情境是互斥的，不會同時發生，每種情境的補償內容也不同。

第一種，非40條法定原因及程序要件完備，雇主要求勞工例假日加班，勞工拒絕：
**例假日加班除40條法定原因外，加班屬違法，勞工得拒絕之。**

第二種，非40條法定原因及程序要件完備，雇主要求勞工例假日加班，勞工同意並出勤：
例假日加班除40條法定原因外，**雖勞工同意加班仍屬違法**，雇主得處79條罰則，**勞工如有出勤之事實，薪資仍應加倍發給**，行政函釋裡面沒有提到是否比照40條內容給予補休，應為**沒有補休**。

第三種，符合40條法定原因及程序要件完備，勞工於例假日加班：
**應給予勞工40條規定之加倍工資及補休。**

說明欄內的說明像是點了一下第一、二種情境，再合併給與第三種情境的補償，但這三種情境是互斥、不會同時發生的。

> 勞基法40條程序要件：
> A.因天災、事變或突發事件
> B.雇主有需要
> C.延長工時開始後24小時內通知工會；無工會者，應報當地主管機關備查。
> D.應於事後補給勞工適當休息。           
> 
> 1.勞基法40條相關行政函釋
> http://tinyurl.com/hc4x5qj
> 
> 2.民國 91 年 03 月 06 日『勞動二 字第 0910010425 號 令』
> 事業單位如非因勞動基準法第四十條所列天災、事變或突發事件等法定原
> 因，而使勞工於該法第三十六條之例假日工作，自屬違法。惟如勞工已有
> 於例假日出勤之事實，其工作時間未超過八小時之部分，不計入該法第三
> 十二條第一項、第二項所定之每月延長工時總時數內；如超過八小時之部
> 分，則應計入。
> 
> 3.民國 90 年 01 月 04 日『(89) 台勞動二 字第 0055954 號』
> 二、勞動基準法第三十六條規定：「勞工每七日中至少應有一日之休息，
> 作為例假」，此項例假依該法規定，事業單位如非因同法第四十條所
> 列天災、事變或突發事件等法定原因，縱使勞工同意，亦不得使勞工
> 在該假日工作。事業單位違反上開法令規定，將依法處理並督責改進
> 。至於勞工如已有於例假日出勤之事實，其當日出勤之工資，仍應加
> 倍發給，另該日工作時間屬該法第三十條所定正常工時後之延長者，
> 依本會八十九年十月二十一日台八十九勞動二字第○○四一五三五號
> 函釋，應計入同法第三十二條第一、二項所定之每月延長工時時數內
> 。該日工作時間如未超過同法第三十條所定之正常工作時間部分，依
> 本會八十年五月二十五日台八十勞動二字第一三一六二號函釋，其工
> 作時數不包括在每月延長工時總時數之內。
> 
> 4..民國 98 年 12 月 08 日『勞動 2 字第 0980088616 號 函』
> 三、另事業單位應依核備後之約定給予例假，其非因同法第 40 條所列天
> 災、事變或突發事件等法定原因，縱使勞工同意，亦不得使勞工在該
> 例假日工作，違反者可依違反同法第 36 條規定論處。

**Comment by git4tw99** [comment]
我同意 @djpcsixth 所言，其實因為情境的不同，要在目前的圖表中表達有困難，但因為有加註後，有變清楚。但兩例中的額外工資是否能常態性? 或是只能偶爾為之? 今日看到  "勞動部公告廢止「例假可挪移」函釋，並宣告八月起生效，引發客運業者不滿，新店客運今天發函給新北與北市交通局，表示從下個月起，新店客運員工將僅上班五天，周六、周日兩天所屬路線班次將全面停駛營運" ；就可以知道過於理想性的法規，有可能傷害的是既有底層勞工的工作權。我個人是認為落實勞動檢查才是目前第一要務。有些勞工的工作性質，與公務員或一般白領差異甚大。這是我們在看待這些法案時，要特別小心注意的。

**Comment by yurenju** [comment]
我正在改， @djpcsixth 與 @git4tw99 覺得這樣如何？

預設條件是兩個都是打勾的。

![image](https://cloud.githubusercontent.com/assets/22155/16776356/84853346-4897-11e6-85ba-733dc6339acc.png)

## 情況一

![image](https://cloud.githubusercontent.com/assets/22155/16776204/e36d3a4e-4896-11e6-9db2-3165768bb409.png)

## 情況二

![image](https://cloud.githubusercontent.com/assets/22155/16776221/00f4a05c-4897-11e6-9be5-a762702d6855.png)

## 情況三

![image](https://cloud.githubusercontent.com/assets/22155/16776231/0c510bc0-4897-11e6-8266-d8bf256f4b7f.png)

**Comment by yurenju** [comment]
先睡了，明天再來看兩位的討論

**Comment by djpcsixth** [comment]
增加了條件設定變得很清楚，如果僅勾選第一項條件應該會與情況四相同，供您參考。謝謝原作者 yurenju的巧思。
