### ISSUE TITLE
勞基法現行版本有誤

### ISSUE THREAD

**Issue by djpcsixth** [g0v/workweek#9]
http://imgur.com/m1CG6MF
在這張圖內**勞基法現行版本**的額外工資應為0元，非400元。

關心勞基法修法的朋友知道，現行勞基法36條漏洞，允許雇主實施777775制變形工時，一周上六天班，只用給予正常月薪，不用給予加班費，因為雇主得主張這六天的工時皆屬正常工時每周40小時內。

> 第 36 條  勞工每七日中至少應有一日之休息，作為例假。

一周內七天，除36條規定的例假日外，其餘六天勞基法皆無定義，雇主得自由安排30條的正常工時40小時於這六天內，因此只要當周工時未滿40小時，雇主都可以主張為正常工時，不給予加班費。

同理，當颱風假或國定假日出現在平日，雇主都可以挪移正常工時於第六天，要勞工第六天補班到一周40小時且不給予加班費，以上都是勞基法現行版本的漏洞。

一例一休版本及二例版本明確定義一周內的兩日，雇主僅剩5日可以分配正常工時，能有效防堵以上漏洞。

附帶一提，工時應分為正常工時及延長工時，各受不同法條限制。一例一休版本的休息日加班要列入月延長工時46小時限制，不計入正常工時，但在畫面呈現上可能會更趨複雜，僅提供意見給您參考，謝謝您。

**Comment by yurenju** [comment]
@djpcsixth 確實有錯，謝謝你抓到這個 bug！修正中
